version: '3'
services:
  Activemq:
    container_name: ActiveMQ
    image: bobcrutchley/activemq
  MongoDB:
    container_name: MongoDB
    image: mongo
Account-Api:
    container_name: Account-Api
    build:
      context: Account-Api
      args:
      - artifact_id=Account-Api
      - version=1.0.0
Account-Number-Generator:
    container_name: Account-Number-Generator
    build:
      context: Account-Number-Generator
      args:
      - artifact_id=Account-Number-Generator
      - version=1.0.0
Account-Prize-Generator:
    container_name: Account-Prize-Generator
    build:
      context: Account-Prize-Generator
      args:
      - artifact_id=Account-Prize-Generator
      - version=1.0.0
Account-Consumer:
    container_name: Account-Consumer
    build:
      context: Account-Consumer
      args:
      - artifact_id=Account-Consumer
      - version=1.0.0
Account-Front-End:
    container_name: Account-Front-End
    build:
      context: Account-Front-End
      args:
      - artifact_id=Account-Front-End
      - version=1.0.0